# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Acheev' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Acheev
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Firebase/Core'
  pod 'FBSDKLoginKit'

end
